// Arabic display names for Kuwait's governorates and areas. The keys are the exact values the
// backend enum (kuwaitGovernorateCities) uses — those are what get saved on orders and
// profiles, so they never change. Only the label shown on Arabic pages comes from here; a value
// missing from this map simply shows in English.
export const PLACE_AR: Record<string, string> = {
  // ── Governorates
  'Al Asimah': 'العاصمة',
  'Al Asimah (Capital)': 'العاصمة',
  Hawalli: 'حولي',
  Farwaniya: 'الفروانية',
  Ahmadi: 'الأحمدي',
  'Al Ahmadi': 'الأحمدي',
  Jahra: 'الجهراء',
  'Al Jahra': 'الجهراء',
  'Mubarak Al-Kabeer': 'مبارك الكبير',

  // ── Al Asimah
  'Kuwait City': 'مدينة الكويت',
  Sharq: 'شرق',
  Mirqab: 'المرقاب',
  Qibla: 'القبلة',
  Dasman: 'دسمان',
  Salhiya: 'الصالحية',
  'Bneid Al-Qar': 'بنيد القار',
  Dasma: 'الدسمة',
  Daiya: 'الدعية',
  Kaifan: 'كيفان',
  Khaldiya: 'الخالدية',
  Mansouriya: 'المنصورية',
  Faiha: 'الفيحاء',
  Nuzha: 'النزهة',
  Shamiya: 'الشامية',
  Rawda: 'الروضة',
  Adailiya: 'العديلية',
  Qadsiya: 'القادسية',
  'Abdullah Al-Salem': 'عبدالله السالم',
  Surra: 'السرة',
  Yarmouk: 'اليرموك',
  Granada: 'غرناطة',
  Qairawan: 'القيروان',
  'Jaber Al-Ahmad': 'جابر الأحمد',
  Sulaibikhat: 'الصليبيخات',
  'North West Sulaibikhat': 'شمال غرب الصليبيخات',
  Doha: 'الدوحة',
  Nahda: 'النهضة',
  'Shuwaikh Residential': 'الشويخ السكني',
  'Shuwaikh Industrial': 'الشويخ الصناعية',
  Failaka: 'فيلكا',

  // ── Hawalli
  Salmiya: 'السالمية',
  Rumaithiya: 'الرميثية',
  Jabriya: 'الجابرية',
  Bayan: 'بيان',
  Mishref: 'مشرف',
  Salwa: 'سلوى',
  'Maidan Hawalli': 'ميدان حولي',
  Bidaa: 'بيدع',
  Shaab: 'الشعب',
  Nugra: 'النقرة',
  Hitteen: 'حطين',
  Zahra: 'الزهراء',
  Salam: 'السلام',
  Siddeeq: 'الصديق',
  'Mubarak Al-Abdullah': 'مبارك العبدالله',
  Shuhada: 'الشهداء',
  Anjafa: 'أنجفة',

  // ── Farwaniya
  'Jleeb Al-Shuyoukh': 'جليب الشيوخ',
  Khaitan: 'خيطان',
  'Abraq Khaitan': 'أبرق خيطان',
  Ardiya: 'العارضية',
  'Ardiya Industrial': 'العارضية الصناعية',
  Andalous: 'الأندلس',
  Ferdous: 'الفردوس',
  'Sabah Al-Nasser': 'صباح الناصر',
  Rehab: 'الرحاب',
  Rabiya: 'الرابية',
  Rai: 'الري',
  Riggae: 'الرقعي',
  Dhajeej: 'الضجيج',
  Omariya: 'العمرية',
  'Abdullah Al-Mubarak': 'عبدالله المبارك',
  Ishbiliya: 'إشبيلية',
  Abbasiya: 'العباسية',

  // ── Ahmadi
  Fahaheel: 'الفحيحيل',
  Mahboula: 'المهبولة',
  Mangaf: 'المنقف',
  'Abu Halifa': 'أبو حليفة',
  Fintas: 'الفنطاس',
  Hadiya: 'هدية',
  Riqqa: 'الرقة',
  'Jaber Al-Ali': 'جابر العلي',
  'Ali Sabah Al-Salem': 'علي صباح السالم',
  Sabahiya: 'الصباحية',
  Egaila: 'العقيلة',
  'Fahad Al-Ahmad': 'فهد الأحمد',
  Dhaher: 'الظهر',
  Wafra: 'الوفرة',
  Zour: 'الزور',
  'Sabah Al-Ahmad Sea City': 'مدينة صباح الأحمد البحرية',
  Shuaiba: 'الشعيبة',
  Julaia: 'الجليعة',

  // ── Jahra
  'Saad Al-Abdullah': 'سعد العبدالله',
  Sulaibiya: 'الصليبية',
  'Sulaibiya Industrial': 'الصليبية الصناعية',
  Naeem: 'النعيم',
  Nasseem: 'النسيم',
  Oyoun: 'العيون',
  Qasr: 'القصر',
  Taima: 'تيماء',
  Waha: 'الواحة',
  Kabd: 'كبد',
  Abdali: 'العبدلي',
  Amghara: 'أمغرة',
  Salmi: 'السالمي',

  // ── Mubarak Al-Kabeer
  'Sabah Al-Salem': 'صباح السالم',
  Adan: 'العدان',
  Qurain: 'القرين',
  Qusour: 'القصور',
  Fnaitees: 'الفنيطيس',
  Messila: 'المسيلة',
  'Abu Al-Hasaniya': 'أبو الحصانية',
  'Abu Futaira': 'أبو فطيرة',
  Wista: 'وسطي',
};
